name: JSON Matrix über Outputs übergeben

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      testmatrix: ${{ steps.create_matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Erstelle JSON Matrix als Output
        shell: python 
        id: create_matrix
        run: |
          # Python-Skript zum Erstellen der JSON-Matrix
          import json
          testmatrix = {
              "group1": ["item1", "items2"],
              "group2": ["item1", "items2", "items3"],
              "group3": ["item1", "items2", "items3", "items4"],
              "group4": ["item1", "items2", "item3", "items4", "item5", "items6"]
          }
          # JSON als kompakter String
          print(f"::set-output name=matrix::{json.dumps(testmatrix)}")
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zeige die übergebene JSON Matrix
        shell: python
        run: |
          raw_matrix = '${{ needs.job1.outputs.testmatrix }}'
          print(raw_matrix)