name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Der Job gibt die Matrix aus

    steps:
      - id: set-matrix
        run: |
          testmatrix='{
            "group1": ["item1", "items2"],
            "group2": ["item1", "items2", "items3"],
            "group3": ["item1", "items2", "items3", "items4"],
            "group4": ["item1", "items2", "item3", "items4", "item5", "items6"]
          }'
          
          matrix_str=$(echo "$testmatrix" | jq -c .)  

          echo "matrix=$matrix_str" >> "$GITHUB_OUTPUT"  

  job2: 
    runs-on: ubuntu-latest
    needs: job1  
    steps:
      - run: |
      
         # Speichern der Matrix in einer Variablen
          MATRIX="${{ needs.job1.outputs.matrix }}"
          
          echo "The stored matrix is: $MATRIX"
          RAW_STRING='$MATRIX'

          FORMATTED_STRING=$(echo "$RAW_STRING" \
            | sed 's/{/{" /g' \
            | sed 's/}/" }/g' \
            | sed 's/:/":"/g' \
            | sed 's/,/", "/g' \
            | sed 's/\[/\[ "/g' \
            | sed 's/\]/" \]/g' \
          )
          echo "$FORMATTED_STRING"


          SECOND_OBJECT=$(echo "$MATRIX" | jq -r '.group2')  
          echo "The second object in group2 is: $SECOND_OBJECT"