name: JSON Matrix über Outputs übergeben

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      testmatrix: ${{ steps.create_matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Erstelle JSON Matrix als Output
        id: create_matrix
        run: |
          # JSON-Daten erstellen
          testmatrix='{
            "group1": ["item1", "items2"],
            "group2": ["item1", "items2", "items3"],
            "group3": ["item1", "items2", "items3", "items4"],
            "group4": ["item1", "items2", "item3", "items4", "item5", "items6"]
          }'
          
          # JSON-Daten bereinigen und als Output setzen
          clean_matrix=$(echo "$testmatrix" | jq -c .)
          echo "::set-output name=matrix::${clean_matrix}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zeige die übergebene JSON Matrix
        run: |
          # Empfangener JSON-Output aus Job1
          echo "Empfangene JSON Matrix:"
          echo "${{ needs.job1.outputs.testmatrix }}"

          # Verarbeite den JSON-String mit jq
          echo "Verarbeitung mit jq:"
          echo "${{ needs.job1.outputs.testmatrix }}" | jq .
