name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Der Job gibt die Matrix aus

    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_ENV
        # Das Ergebnis der Matrix wird in die Umgebungsvariable $GITHUB_ENV geschrieben

  job2: 
    runs-on: ubuntu-latest
    needs: job1  
    steps:
      - run: |
      
         # Speichern der Matrix in einer Variablen
          MATRIX="${{ needs.job1.outputs.matrix }}"
          
          # Ausgabe der Matrix
          echo "The stored matrix is: $MATRIX"