name: JSON Matrix über Outputs übergeben

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    env: 
      DOTNET_INSTALL_DIR: "/home/runner/.dotnet"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup dotnet^
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json