name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Der Job gibt die Matrix aus

    steps:
      - id: set-matrix
        run: |
          testmatrix='{
            "group1": ["item1", "items2"],
            "group2": ["item1", "items2", "items3"],
            "group3": ["item1", "items2", "items3", "items4"],
            "group4": ["item1", "items2", "item3", "items4", "item5", "items6"]
          }'
          
          matrix_str=$(echo "$testmatrix" | jq -c .)  
          
          echo "'matrix=$matrix_str'" >> "$GITHUB_OUTPUT"  

  job2: 
    runs-on: ubuntu-latest
    needs: job1  
    steps:
      - run: |
      
         # Speichern der Matrix in einer Variable
          MATRIX=${{ needs.job1.outputs.matrix }}
          
          echo "The raw matrix from job1 is: $MATRIX"  # Print out the raw matrix for debugging

          # Parse the JSON string back into a usable JSON object
          PARSED_MATRIX=$(echo "$MATRIX" | jq .)

          echo "The PARSED matrix from job1 is: $PARSED_MATRIX" 
          SECOND_OBJECT=$(echo "$MATRIX" | jq -r '.group2')  
          echo "The second object in group2 is: $SECOND_OBJECT"